name: CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4', '8.5']
        experimental: [false]
        include:
          - php: '8.6'
            experimental: true

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-progress ${{ matrix.experimental && '--ignore-platform-req=php+' || '' }}

      - name: PHP guideline is up to date
        run: php bin/generate-guideline.php --check

      - name: Manifest is up to date
        run: php bin/generate-manifest.php --check

      - name: Lint (Pint)
        run: ./vendor/bin/pint --test

      - name: Lint (PHP_CodeSniffer)
        run: ./vendor/bin/phpcs

      - name: Tests (Pest)
        run: composer test
